# Generated by Django 2.0.7 on 2018-07-29 12:48

import bills.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('initiators', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgendaQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Створено')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='Змінено')),
                ('slug', models.SlugField(unique=True, verbose_name='Посилання')),
                ('title', models.CharField(max_length=512, verbose_name='Заголовок')),
                ('question_type', models.PositiveSmallIntegerField(choices=[(1, 'Реєстрація'), (0, 'Голосування'), (8, 'Промова')])),
                ('id_event', models.PositiveIntegerField(verbose_name='ID події')),
                ('vote_for', models.PositiveSmallIntegerField(verbose_name='За')),
                ('vote_against', models.PositiveSmallIntegerField(verbose_name='Проти')),
                ('vote_abstain', models.PositiveSmallIntegerField(verbose_name='Утрималися')),
                ('not_voting', models.PositiveSmallIntegerField(verbose_name='Не голосували')),
                ('present', models.PositiveSmallIntegerField(verbose_name='Присутні')),
                ('absent', models.PositiveSmallIntegerField(verbose_name='Відсутні')),
                ('total', models.PositiveSmallIntegerField(verbose_name='Загалом')),
            ],
            options={
                'ordering': ('-created',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Створено')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='Змінено')),
                ('slug', models.SlugField(unique=True, verbose_name='Посилання')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('rada_id', models.PositiveIntegerField(verbose_name='ID у ВР')),
                ('number', models.PositiveIntegerField(verbose_name='Реєстраційний номер')),
                ('convocation', models.PositiveSmallIntegerField(choices=[(8, 'VIII скликання')], default=8)),
                ('session', models.CharField(max_length=30, verbose_name='Сесія')),
                ('rubric', models.CharField(max_length=50, verbose_name='Рубрика')),
                ('subject', models.CharField(max_length=50, verbose_name="Суб'єкт")),
                ('bill_type', models.CharField(max_length=50, verbose_name='Тип')),
                ('phase', models.CharField(max_length=200, verbose_name='Фаза')),
                ('phase_date', models.DateField(verbose_name='Дата фази')),
                ('registration_date', models.DateTimeField(null=True, verbose_name='Дата реєстрації')),
                ('agenda_uri', models.URLField(blank=True, null=True, verbose_name='Посилання на порядок дений')),
                ('committee_date_passed', models.DateField(blank=True, null=True, verbose_name='Дата фази')),
                ('alternatives', models.ManyToManyField(related_name='_bill_alternatives_+', to='bills.Bill')),
                ('authors', models.ManyToManyField(related_name='authored', to='initiators.Initiator')),
                ('bind_bills', models.ManyToManyField(related_name='_bill_bind_bills_+', to='bills.Bill')),
            ],
            options={
                'verbose_name_plural': 'bills',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Створено')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='Змінено')),
                ('slug', models.SlugField(unique=True, verbose_name='Посилання')),
                ('document_type', models.CharField(max_length=50, verbose_name='Тип')),
                ('phase_date', models.DateField(verbose_name='Дата')),
                ('uri', models.URLField(blank=True, null=True, verbose_name='Посилання на порядок дений')),
                ('document_file', models.FileField(upload_to=bills.models.bill_directory_path)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='bills.Bill')),
            ],
            options={
                'ordering': ('-created',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Passing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Створено')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='Змінено')),
                ('slug', models.SlugField(unique=True, verbose_name='Посилання')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('date', models.DateField(verbose_name='Дата')),
            ],
            options={
                'verbose_name_plural': 'passings',
            },
        ),
        migrations.AddField(
            model_name='bill',
            name='chronology',
            field=models.ManyToManyField(related_name='bills', to='bills.Passing'),
        ),
        migrations.AddField(
            model_name='bill',
            name='executives',
            field=models.ManyToManyField(related_name='bills_to_execute', to='initiators.Initiator'),
        ),
        migrations.AddField(
            model_name='bill',
            name='main_executives',
            field=models.ManyToManyField(related_name='main_bills_to_execute', to='initiators.Initiator'),
        ),
        migrations.AddField(
            model_name='agendaquestion',
            name='bills',
            field=models.ManyToManyField(related_name='agenda_questions', to='bills.Bill'),
        ),
    ]
