# Generated by Django 2.0.7 on 2018-08-02 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initiators', '0003_auto_20180730_1636'),
        ('bills', '0002_auto_20180730_0954'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='initiators',
            field=models.ManyToManyField(blank=True, related_name='initiated', to='initiators.Initiator'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='alternatives',
            field=models.ManyToManyField(blank=True, related_name='_bill_alternatives_+', to='bills.Bill'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='authors',
            field=models.ManyToManyField(blank=True, related_name='authored', to='initiators.Initiator'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='bind_bills',
            field=models.ManyToManyField(blank=True, related_name='_bill_bind_bills_+', to='bills.Bill'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='chronology',
            field=models.ManyToManyField(blank=True, related_name='bills', to='bills.Passing'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='committees',
            field=models.ManyToManyField(blank=True, related_name='bills', through='bills.WorkOuts', to='committees.Committee'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='executives',
            field=models.ManyToManyField(blank=True, related_name='bills_to_execute', to='initiators.Initiator'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='main_executives',
            field=models.ManyToManyField(blank=True, related_name='main_bills_to_execute', to='initiators.Initiator'),
        ),
    ]
