# Generated by Django 2.0.7 on 2018-09-04 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0003_auto_20180802_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passing',
            name='slug',
            field=models.SlugField(max_length=512, null=True, unique=True, verbose_name='Посилання'),
        ),
    ]
