# Generated by Django 2.0.7 on 2018-09-04 13:57

import bills.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0004_auto_20180904_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document_file',
            field=models.FileField(blank=True, null=True, upload_to=bills.models.bill_directory_path),
        ),
    ]
