# Generated by Django 2.0.7 on 2018-09-07 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0005_auto_20180904_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='convocation',
            field=models.CharField(max_length=25, verbose_name='Скликання'),
        ),
    ]
