# Generated by Django 2.0.7 on 2018-09-07 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0007_auto_20180907_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='number',
            field=models.CharField(max_length=25, verbose_name='Реєстраційний номер'),
        ),
    ]
