# Generated by Django 2.0.7 on 2018-09-10 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0008_auto_20180907_2039'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bill',
            old_name='rada_id',
            new_name='bill_id',
        ),
    ]
