# Generated by Django 2.0.7 on 2018-09-12 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0011_auto_20180911_1535'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='committee_date_passed',
        ),
    ]
