# Generated by Django 2.0.7 on 2018-09-12 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0014_auto_20180912_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.CharField(max_length=512, verbose_name='Тип'),
        ),
    ]
