# Generated by Django 2.0.7 on 2018-07-30 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('committees', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workouts',
            name='bill',
        ),
        migrations.RemoveField(
            model_name='workouts',
            name='committee',
        ),
        migrations.DeleteModel(
            name='WorkOuts',
        ),
    ]
