# Generated by Django 2.0.7 on 2018-07-30 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('committees', '0002_auto_20180730_0850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='committee',
            name='slug',
            field=models.SlugField(max_length=512, unique=True, verbose_name='Посилання'),
        ),
    ]
