# Generated by Django 2.0.7 on 2018-08-02 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('committees', '0003_auto_20180730_0926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='committee',
            name='description',
            field=models.CharField(blank=True, max_length=512, verbose_name='Опис'),
        ),
        migrations.AlterField(
            model_name='committee',
            name='head',
            field=models.CharField(blank=True, max_length=200, verbose_name='Голова'),
        ),
    ]
