# Generated by Django 2.0.7 on 2018-07-29 12:48

from django.db import migrations, models
import django.utils.timezone
import easy_thumbnails.fields
import initiators.models
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Initiator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Створено')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='Змінено')),
                ('slug', models.SlugField(unique=True, verbose_name='Посилання')),
                ('first_name', models.CharField(max_length=50, verbose_name="Ім'я")),
                ('last_name', models.CharField(max_length=100, verbose_name='Прізвище')),
                ('middle_name', models.CharField(blank=True, max_length=100, verbose_name='По батькові')),
                ('convocation', models.PositiveSmallIntegerField(choices=[(8, 'VIII скликання')], default=8)),
                ('party', models.CharField(blank=True, max_length=200, verbose_name='Партія')),
                ('faction', models.CharField(blank=True, max_length=200, verbose_name='Фракція')),
                ('information', models.CharField(blank=True, max_length=512, verbose_name='Інформація')),
                ('email', models.EmailField(blank=True, max_length=90, verbose_name='Емейл')),
                ('phone', models.CharField(blank=True, max_length=90, verbose_name='Телефон')),
                ('photo_manual', easy_thumbnails.fields.ThumbnailerImageField(blank=True, upload_to=initiators.models.photo_upload_to)),
            ],
            options={
                'verbose_name_plural': 'initiators',
            },
        ),
    ]
