# Generated by Django 2.0.7 on 2018-07-30 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initiators', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='initiator',
            name='slug',
            field=models.SlugField(max_length=512, unique=True, verbose_name='Посилання'),
        ),
    ]
