# Generated by Django 2.0.7 on 2018-07-30 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('initiators', '0002_auto_20180730_0926'),
    ]

    operations = [
        migrations.RenameField(
            model_name='initiator',
            old_name='photo_manual',
            new_name='photo',
        ),
    ]
