# Generated by Django 2.0.7 on 2018-09-03 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initiators', '0003_auto_20180730_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='initiator',
            name='rada_id',
            field=models.PositiveSmallIntegerField(default=5625),
        ),
    ]
