# Generated by Django 2.0.7 on 2018-09-03 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initiators', '0004_initiator_rada_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='initiator',
            name='rada_id',
            field=models.PositiveSmallIntegerField(unique=True),
        ),
    ]
