# Generated by Django 2.0.7 on 2018-09-06 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initiators', '0005_auto_20180903_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='initiator',
            name='information',
            field=models.CharField(blank=True, max_length=2000, verbose_name='Інформація'),
        ),
    ]
