# Generated by Django 2.0.7 on 2018-09-10 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('committees', '0004_auto_20180802_1903'),
        ('initiators', '0006_auto_20180906_1101'),
    ]

    operations = [
        migrations.AddField(
            model_name='initiator',
            name='committees',
            field=models.ManyToManyField(blank=True, related_name='initiators', to='committees.Committee'),
        ),
        migrations.AddField(
            model_name='initiator',
            name='person_id',
            field=models.PositiveSmallIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='initiator',
            name='rada_id',
            field=models.PositiveSmallIntegerField(blank=True, null=True, unique=True),
        ),
    ]
