# Generated by Django 2.0.7 on 2018-09-11 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initiators', '0008_auto_20180910_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='initiator',
            name='organization',
            field=models.CharField(blank=True, max_length=90, verbose_name='Організація'),
        ),
        migrations.AddField(
            model_name='initiator',
            name='post',
            field=models.CharField(blank=True, max_length=90, verbose_name='Посада'),
        ),
        migrations.AlterField(
            model_name='initiator',
            name='convocation',
            field=models.CharField(blank=True, max_length=25, verbose_name='Скликання'),
        ),
    ]
