# Generated by Django 2.0.7 on 2018-09-13 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('initiators', '0010_auto_20180913_1629'),
    ]

    operations = [
        migrations.RenameField(
            model_name='initiator',
            old_name='convocation',
            new_name='convocations',
        ),
    ]
